### ISSUE TITLE
Too many arguments for function: cs#CrateSelected

### ISSUE THREAD

**Issue by 0x8f701** [martskins/vim-cargo-search#1]
Hi, thanks for making this plugin, I had this error after hitted enter:

![image](https://user-images.githubusercontent.com/33961674/86542789-24295e80-bf19-11ea-9d69-d15398cf464b.png)

This error doesn't happen in neovim0.4.3 just in vim8.2

**Comment by 0x8f701** [comment]
Also I didn't find a way to cancel it

**Comment by martskins** [comment]
Thank you for reporting this! It seems like I misunderstood how `popup_menu` works in vim. 

Just pushed a fix for this, so if you update it should be working for you. Do let me know if anything else comes up.

**Comment by 0x8f701** [comment]
@martskins It starts to work in vim. thanks, how can we cancel it if I don't find what I want?

**Comment by martskins** [comment]
`<ESC>` should close the popup without moving to `Cargo.toml`.

**Comment by 0x8f701** [comment]
Another point is, if we can using `CTRL+J` and `CTRL+K` to switch between items, it'll be great

**Comment by 0x8f701** [comment]
@martskins 

> <ESC> should close the popup without moving to Cargo.toml.

Just tried in vim it still goes to `Cargo.toml`, but yes in neovim it works

**Comment by martskins** [comment]
> Just tried in vim it still goes to Cargo.toml

Ah yeah, sorry, this works in neovim. I didn't handle this correctly in vim. Pushing a fix for that now.

**Comment by 0x8f701** [comment]
@martskins Great,  thanks! It's really useful to have this tool in (neo)vim!
